version: "3.8"

services:
    app:
        image: php:$PHP_VERSION
        ports:
            - "8080:8080"
        volumes:
            - $ROOT_DIR:/app
            - ./entrypoint.sh:/entrypoint.sh
        environment:
            DOCUMENT_ROOT: $DOCUMENT_ROOT
            EXTENSIONS: $PHP_EXTENSIONS
            SETUP_SCRIPT: $SETUP_SCRIPT
            # MySQL
            DB_HOST: $DB_HOST
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_NAME: $DB_NAME
            DATABASE_URL: $DATABASE_URL
            # Redis
            REDIS_HOST: $REDIS_HOST
        working_dir: /app
        entrypoint: /entrypoint.sh
        extra_hosts:
            - host.docker.internal:host-gateway
