version: "3.8"

services:
    app:
        image: $APP_IMAGE
        build:
            dockerfile: app/Dockerfile
            args:
                PHP_VERSION: $PHP_VERSION
                PHP_EXTENSIONS: $PHP_EXTENSIONS
                PACKAGES: $PACKAGES
                USER_ID: $USER_ID
        ports:
            - "8080:8080"
        volumes:
            - $PWD:/app
            - ./app/entrypoint.sh:/entrypoint.sh
        environment:
            DOCUMENT_ROOT: $DOCUMENT_ROOT
            SETUP_SCRIPT: $SETUP_SCRIPT
            # MySQL
            DB_HOST: ${DB_HOST:-}
            DB_USER: ${DB_USER:-}
            DB_PASSWORD: ${DB_PASSWORD:-}
            DB_NAME: ${DB_NAME:-}
            DATABASE_URL: ${DATABASE_URL:-}
            # Redis
            REDIS_HOST: ${REDIS_HOST:-}
        working_dir: /app
        entrypoint: /entrypoint.sh
        extra_hosts:
            - host.docker.internal:host-gateway
