version: "3.8"

services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data-mysql:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    data-mysql:
