version: "3.8"

services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - data-mysql:/var/lib/mysql
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        ports:
            - 8282:8080

volumes:
    data-mysql:
